Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject_AscentApp.Models
{
    public class Customer
    {

        public Customer()
        {

        }

        public int CustomerID { get; set; }
        public string CompanyName { get; set; }
        public int Credit { get; set; }
        public int MoneySpent { get; set; }
        public string PhoneNumber { get; set; }
        public string CustomerEmail { get; set; }

    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProject_AscentApp.Models
{
    public class Employee
    {
        public Employee()
        {

        }

        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Sales { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace FinalProject_AscentApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject_AscentApp.Models;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace FinalProject_AscentApp.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepo repo;

        public CustomerController(ICustomerRepo repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
           
           
                var customers = repo.GetAllCustomers();

                return View(customers);
            
           
        }

        [HttpGet]
        public async Task<IActionResult> Index(string custSearch)
        {
            
            ViewData["GetCustomerDetails"] = custSearch;

            var custQuery = from x in repo.GetAllCustomers() select x;
            if(!String.IsNullOrEmpty(custSearch))
            {
                custQuery = custQuery.Where(s => !string.IsNullOrEmpty(s.CompanyName) && s.CompanyName.Contains(custSearch));
            }
            return View(custQuery);

        }

        public IActionResult ViewCustomer(int id)
        {
            var customer = repo.GetCustomer(id);
            return View(customer);
        }

        public IActionResult UpdateCustomer(int id)
        {
            var customer = repo.GetCustomer(id);

            if (customer == null)
            {
                return View("CustomerNotFound");
            }

            return View(customer);
        }

        public IActionResult UpdateCustomerToDatabase(Customer customer)
        {
            repo.UpdateCustomer(customer);

            return RedirectToAction("ViewCustomer", new { id = customer.CustomerID });
        }


        public IActionResult InsertCustomerToDatabase(Customer customerToInsert)
        {
            repo.InsertCustomer(customerToInsert);

            return RedirectToAction("Index");
        }
        public IActionResult InsertCustomer(Customer customer)
        {
            repo.InsertCustomer(customer);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteCustomer(Customer customer)
        {
            repo.DeleteCustomer(customer);

            return RedirectToAction("Index");
        }
    }
}

Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FinalProject_AscentApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject_AscentApp.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepo repo;

        public EmployeeController(IEmployeeRepo repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            var employees = repo.GetAllEmployees();

            return View(employees);
        }
        [HttpGet]
        public async Task<IActionResult> Index(string empSearch)
        {
            ViewData["GetEmployeeDetails"] = empSearch;
            
            var empQuery = from x in repo.GetAllEmployees() select x;
            if (!String.IsNullOrEmpty(empSearch))
            {
                empQuery = empQuery.Where(s => !string.IsNullOrEmpty(s.LastName) && s.LastName.Contains(empSearch));
            }
            return View(empQuery);

        }

        public IActionResult ViewEmployee(int id)
        {
            var employee = repo.GetEmployee(id);
            return View(employee);
        }

        public IActionResult UpdateEmployee(int id)
        {
            var employee = repo.GetEmployee(id);

            if (employee == null)
            {
                return View("EmployeeNotFound");
            }

            return View(employee);
        }

        public IActionResult UpdateEmployeeToDatabase(Employee employee)
        {
            repo.UpdateEmployee(employee);

            return RedirectToAction("ViewEmployee", new { id = employee.EmployeeID });
        }

        public IActionResult InsertEmployee(Employee employeeToInsert)
        {
            repo.InsertEmployee(employeeToInsert);

            return RedirectToAction("Index");
        }

        public IActionResult InsertEmployeeToDatabase(Employee employeeToInsert)
        {
            repo.InsertEmployee(employeeToInsert);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteEmployee (Employee employee)
        {
            repo.DeleteEmployee(employee);

            return RedirectToAction("Index");
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FinalProject_AscentApp.Models;
using Microsoft.AspNetCore.Authorization;
using System.Dynamic;
using System.Data;

namespace FinalProject_AscentApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IDbConnection conn;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Customer/Index.cshtml
@model IEnumerable<Customer>


<div style="display: block">
    <a href="/Customer/InsertCustomer/">Create a New Customer</a>
</div>

<form method="get" asp-action="Index">
    <p>
        <input class="form-control bg-white border-0 small" type="search" placeholder="Enter Company Name..." value="@ViewData["GetCustomerData"]"  name="custSearch" style="width:500px;" />
            <input type="submit" value="Search" class="btn btn-primary" />
        <a asp-action="Index">Get All Customers</a>
     </p>
</form>


<h2>Customers</h2>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Company Name</th>
        <th>Credit</th>
        <th>Financial History</th>
        <th>Phone Number</th>
        <th>Email</th>
    </tr>

    @foreach (var customer in Model)
    {
<tr>
    <td>@customer.CustomerID</td>
    <td>@customer.CompanyName</td>
    <td>@customer.Credit</td>
    <td>@customer.MoneySpent</td>
    <td>@customer.PhoneNumber</td>
    <td>@customer.CustomerEmail</td>
    <td><a href=/Customer/ViewCustomer/@customer.CustomerID>Edit</a></td>

</tr>

    }
</table>

Views/Customer/InsertCustomer.cshtml
@model Customer
<h2>Create a New Customer</h2>
@using (Html.BeginForm("InsertCustomerToDatabase", "Customer", "Post"))
{
        <input asp-for="CustomerID" type="hidden" value="" />
        <label asp-for="CompanyName" class="control-label">Company Name</label>
        <input type="text" name="CompanyName" class="form-control" value="" />
        <label asp-for="Credit" class="control-label">Credit</label>
        <input type="number" step="0.01" name="Credit" class="form-control" />
        <label asp-for="MoneySpent" class="control-label">Money Spent</label>
        <input type="number" step="0.01" name="MoneySpent" class="form-control" />
        <label asp-for="PhoneNumber" class="control-label">Phone Number</label>
        <input type="text" name="PhoneNumber" class="form-control" value="" />
        <label asp-for="CustomerEmail" class="control-label">Customer Email</label>
        <input type="text" name="CustomerEmail" class="form-control" value=""/>

  


}

Views/Customer/UpdateCustomer.cshtml
@model Customer

<h2>Update @Model.CompanyName</h2>

@using (Html.BeginForm("UpdateCustomerToDatabase", "Customer", "Post"))
{
    <input asp-for="CustomerID" type="hidden" value="@Model.CustomerID" />

    <label asp-for="CompanyName" class="control-label">Company Name</label>

    <input type="text" name="CompanyName" class="form-control" value="@Model.CompanyName" />

    <label asp-for="Credit" class="control-label">Credit</label>

    <input type="number" step="0.01" name="Credit" class="form-control" value="@Model.Credit" />

    <label asp-for="MoneySpent" class="control-label">Money Spent</label>

    <input type="number" step="0.01" name="MoneySpent" class="form-control" value="@Model.MoneySpent" />

    <label asp-for="PhoneNumber" class="control-label">Phone Number</label>

    <input type="text" name="PhoneNumber" class="form-control" value="@Model.PhoneNumber" />

    <label asp-for="CustomerEmail" class="control-label">Email</label>

    <input type="text" name="CustomerEmail" class="form-control" value="@Model.CustomerEmail" />
    <br/>

    <input type="submit" value="Update Customer" class="btn btn-primary" />

}

Views/Customer/ViewCustomer.cshtml
@model Customer

<h3>@Model.CompanyName Information</h3>

<table class="table">
    <tr>
        <th>Customer ID</th>
        <th>Company Name</th>
        <th>Credit</th>
        <th>Financial History</th>
        <th>Phone Number</th>
        <th>Email</th>
    </tr>
    <tr>
        <td>@Model.CustomerID</td>
        <td>@Model.CompanyName</td>
        <td>@Model.Credit</td>
        <td>@Model.MoneySpent</td>
        <td>@Model.PhoneNumber</td>
        <td>@Model.CustomerEmail</td>
    </tr>

</table>

<div style="display: block">
    <a href="/Customer/UpdateCustomer/@Model.CustomerID">Update this Customer</a>
</div>
<br />
<div style="display: block">
    @using (Html.BeginForm("DeleteCustomer", "Customer", "Post"))
    {
        <input type="hidden" asp-for="CustomerID" value="@Model.CustomerID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this customer" />
    }
</div>

Views/Employee/Index.cshtml
@model IEnumerable<Employee>



<div style="display: block">
   <a href="/Employee/InsertEmployee/">Create a New Employee</a>
</div>

<form method="get" asp-action="Index">
    <p>
        <input class="form-control bg-white border-0 small" type="search" placeholder="Enter Employee's Last Name..." value="@ViewData[" GetCustomerDetails"]" name="empSearch" style="width:500px;" />
        <input type="submit" value="Search" class="btn btn-primary" />
        <a asp-action="Index">Get All Employees</a>
    </p>
</form>

<h2>Employees</h2>
<table class="table">
    <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Password</th>
        <th>Sales</th>
    </tr>

    @foreach (var employee in Model)
    {
        <tr>
            <td>@employee.EmployeeID</td>
            <td>@employee.FirstName</td>
            <td>@employee.LastName</td>
            <td>@employee.Email</td>
            <td>@employee.Password</td>
            <td>@employee.Sales</td>
            <td><a href=/Employee/ViewEmployee/@employee.EmployeeID>Edit</a></td>

        </tr>

    }
</table>

Views/Employee/InsertEmployee.cshtml
@model Employee
<h2>Create a New Employee</h2>
@using (Html.BeginForm("InsertEmployeeToDatabase", "Employee", "Post"))
{
    <input asp-for="EmployeeID" type="hidden" value="" />
    <label asp-for="FirstName" class="control-label">First Name</label>
    <input type="text" name="FirstName" class="form-control" value="" />
    <label asp-for="LastName" class="control-label">First Name</label>
    <input type="text" name="FirstName" class="form-control" value="" />
    <label asp-for="Email" class="control-label">Email</label>
    <input type="text" name="Email" class="form-control" value="" />
    <label asp-for="Password" class="control-label">Password</label>
    <input type="text" name="FirstName" class="form-control" value="" />
    <label asp-for="Sales" class="control-label">Sales</label>
    <input type="number" step="0.01" name="Sales" class="form-control" />

}

Views/Employee/UpdateEmployee.cshtml
@model Employee

<h2>Update @Model.LastName</h2>

@using (Html.BeginForm("UpdateEmployeeToDatabase", "Employee", "Postt"))
{
    <input asp-for="EmployeeID" type="hidden" value="@Model.EmployeeID" />

    <label asp-for="FirstName" class="control-label">First Name</label>

    <input type="text" name="FirstName" class="form-control" value="@Model.FirstName" />

    <label asp-for="LastName" class="control-label">Last Name</label>

    <input type="text" name="LastName" class="form-control" value="@Model.LastName" />

    <label asp-for="Email" class="control-label">Email</label>

    <input type="text" name="Email" class="form-control" value="@Model.Email" />

    <label asp-for="Password" class="control-label">Password</label>

    <input type="text" name="Password" class="form-control" value="@Model.Password" />

    <label asp-for="Sales" class="control-label">Sales</label>

    <input type="number" step="0.01" name="Sales" class="form-control" value="@Model.Sales" />
    <br/>

    <input type="submit" value="Update Customer" class="btn btn-primary" />

}

Views/Employee/ViewEmployee.cshtml
@model Employee

<h3>@Model.FirstName @Model.LastName</h3>

<table class="table">
    <tr>
        <th>Employee ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Password</th>
        <th>Sales</th>
    </tr>
    <tr>
        <td>@Model.EmployeeID</td>
        <td>@Model.FirstName</td>
        <td>@Model.LastName</td>
        <td>@Model.Email</td>
        <td>@Model.Password</td>
        <td>@Model.Sales</td>
    </tr>

</table>

<div style="display: block">
    <a href="/Employee/UpdateEmployee/@Model.EmployeeID">Update this Employee</a>
</div>
<br />
<div style="display: block">
    @using (Html.BeginForm("DeleteEmployee", "Employee", "Post"))
    {
        <input type="hidden" asp-for="EmployeeID" value="@Model.EmployeeID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this employee" />
    }

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Reports</h1>
</div>

<!-- Content Row -->

<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Earnings (Monthly)
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">$55,000</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Annual) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Earnings (Annual)
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">$55,000</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Red Mountain Logistics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    <link href="~/lib/bootstrap/dist/css/sb-admin-2.css" rel="stylesheet" />

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">


</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-secondary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fab fa-mountain"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Red Mountain Logistics</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Databases
            </div>

            <!-- Nav Item - Customers Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Customers</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Customer Options:</h6>
                        <a class="collapse-item" asp-area="" asp-controller="Customer" asp-action="Index">Get All Customers</a>
                        <a class="collapse-item" href="/Customer/InsertCustomer/">Create New Customer</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Employees Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Employees</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Employee Pages:</h6>
                        <a class="collapse-item" asp-area="" asp-controller="Employee" asp-action="Index">Get All Employees</a>
                        <a class="collapse-item" href="/Employee/InsertEmployee/">Create New Employee</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading
    
            <div class="sidebar-heading">
                Home
            </div> --!>




            <!-- Nav Item - Home -->
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Home</span>
                </a>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>


        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                  

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        
                       
                           
                       
                    </ul>
                </nav> 
                <!-- End of Topbar -->
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
                <footer class="border-top footer text-muted">
                    <div class="container">
                        &copy; 2021 - FinalProject_AscentApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </div>
                </footer>
                <script src="~/js/sb-admin-2.js"></script>
                <script src="~/lib/jquery/dist/jquery.min.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
                <script src="~/js/site.js" asp-append-version="true"></script>
                @RenderSection("Scripts", required: false)
                <!-- Bootstrap core JavaScript-->
                <script src="vendor/jquery/jquery.min.js"></script>
                <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

                <!-- Core plugin JavaScript-->
                <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

                <!-- Custom scripts for all pages-->
                <script src="js/sb-admin-2.min.js"></script>

                <!-- Page level plugins -->
                <script src="vendor/chart.js/Chart.min.js"></script>

                <!-- Page level custom scripts -->
                <script src="js/demo/chart-area-demo.js"></script>
                <script src="js/demo/chart-pie-demo.js"></script>

</body>
</html>